version: "3"
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - /home/ubuntu/Data_EngineeringII_Project/data/spark-master-data:/opt/spark/data
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/ubuntu/Data_EngineeringII_Project/data/spark-worker-1-data:/opt/spark/data
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/ubuntu/Data_EngineeringII_Project/data/spark-worker-2-data:/opt/spark/data
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
